group3_sbs/group3_sbs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import global_templates.views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls', namespace='login')),
    url(r'^login/', include('login.urls', namespace='login')),
    url(r'^internal/', include('internal.urls', namespace='internal')),
    url(r'^external/', include('external.urls', namespace='external')),
    url(r'^reset/', include('reset.urls', namespace='reset')),
    url(r'^create/', include('create.urls', namespace='create')),
    url(r'^favicon.ico', global_templates.views.stop_favicon),
    url(r'^.*', include('login.urls', namespace='login')),
]

group3_sbs/internal/urls.py
from django.conf.urls import url
from . import views

app_name = 'internal'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cron_job/cron_job_late_charge/$', views.bineeta_cron_job_late_charge, name='bineeta_cron_job_late_charge'),
    url(r'^cron_job/cron_job_late_charge/validate/$', views.bineeta_cron_job_late_charge_validate, name='bineeta_cron_job_late_charge_validate'),
    url(r'^cron_job/cron_job_daily_late_charge/validate/$', views.bineeta_cron_job_daily_late_charge_validate, name='bineeta_cron_job_daily_late_charge_validate'),
    url(r'^error/$', views.error, name='error'),
    url(r'^external_user/checking_account/(?P<external_user_id>[1-9][0-9]*)/view/$', views.view_external_user_checking_account, name='view_external_user_checking_account'),
    url(r'^external_user/credit_card/(?P<external_user_id>[1-9][0-9]*)/view/$', views.view_external_user_credit_card, name='view_external_user_credit_card'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/deactivate/$', views.validate_deactivate_external_user, name='validate_deactivate_external_user'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/edit/$', views.edit_external_user_profile, name='edit_external_user_profile'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/edit/validate/$', views.validate_profile_edit, name='validate_profile_edit'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/reactivate/$', views.validate_reactivate_external_user, name='validate_reactivate_external_user'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/view/$', views.view_external_user_profile, name='view_external_user_profile'),
    url(r'^external_user/request_access/$', views.external_user_access_request, name='external_user_access_request'),
    url(r'^external_user/request_access/validate/$', views.validate_external_user_access_request, name='validate_external_user_access_request'),
    url(r'^external_user/savings_account/(?P<external_user_id>[1-9][0-9]*)/view/$', views.view_external_user_savings_account, name='view_external_user_savings_account'),
    url(r'^internal_user/profile/create/$', views.create_internal_user, name='create_internal_user'),
    url(r'^internal_user/profile/create/validate/$', views.validate_create_internal_user, name='validate_create_internal_user'),
    url(r'^internal_user/profile/edit/$', views.edit_own_profile, name='edit_own_profile'),
    url(r'^internal_user/profile/edit/validate/$', views.validate_own_profile_edit, name='validate_own_profile_edit'),
    url(r'^internal_user/profile/view/$', views.view_own_profile, name='view_own_profile'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/deactivate/$', views.validate_deactivate_internal_user, name='validate_deactivate_internal_user'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/edit/$', views.edit_internal_user_profile, name='edit_internal_user_profile'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/edit/validate/$', views.validate_internal_profile_edit, name='validate_internal_profile_edit'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/reactivate/$', views.validate_reactivate_internal_user, name='validate_reactivate_internal_user'),
    url(r'^internal_user/request_access/$', views.internal_user_access_request, name='internal_user_access_request'),
    url(r'^internal_user/request_access/validate/$', views.validate_internal_user_access_request, name='validate_internal_user_access_request'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/view/$', views.view_internal_user_profile, name='view_internal_user_profile'),
    url(r'^log/create/clear/$', views.validate_clear_create_log, name='validate_clear_create_log'),
    url(r'^log/create/view/$', views.view_create_log, name='view_create_log'),
    url(r'^log/external/clear/$', views.validate_clear_external_log, name='validate_clear_external_log'),
    url(r'^log/external/view/$', views.view_external_log, name='view_external_log'),
    url(r'^log/internal/clear/$', views.validate_clear_internal_log, name='validate_clear_internal_log'),
    url(r'^log/internal/view/$', views.view_internal_log, name='view_internal_log'),
    url(r'^log/login/clear/$', views.validate_clear_login_log, name='validate_clear_login_log'),
    url(r'^log/login/view/$', views.view_login_log, name='view_login_log'),
    url(r'^log/reset/clear/$', views.validate_clear_reset_log, name='validate_clear_reset_log'),
    url(r'^log/reset/view/$', views.view_reset_log, name='view_reset_log'),
    url(r'^log/select_log/clear/$', views.clear_log, name='clear_log'),
    url(r'^log/server/clear/$', views.validate_clear_server_log, name='validate_clear_server_log'),
    url(r'^log/server/view/$', views.view_server_log, name='view_server_log'),
    url(r'^transaction/external_critical/$', views.critical_transactions, name='critical_transactions'),
    url(r'^transaction/external_critical/(?P<transaction_id>[1-9][0-9]*)/approve/$', views.validate_critical_transaction_approval, name='validate_critical_transaction_approval'),
    url(r'^transaction/external_critical/(?P<transaction_id>[1-9][0-9]*)/delete/$', views.validate_delete_critical_transaction, name='validate_delete_critical_transaction'),
    url(r'^transaction/external_critical/(?P<transaction_id>[1-9][0-9]*)/deny/$', views.validate_critical_transaction_denial, name='validate_critical_transaction_denial'),
    url(r'^transaction/external_noncritical/$', views.noncritical_transactions, name='noncritical_transactions'),
    # url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/edit/$', views.edit_noncritical_transaction, name='edit_noncritical_transaction'),
    # url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/edit/validate/$', views.validate_edit_noncritical_transaction, name='validate_edit_noncritical_transaction'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/approve/$', views.validate_noncritical_transaction_approval, name='validate_noncritical_transaction_approval'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/delete/$', views.validate_delete_noncritical_transaction, name='validate_delete_noncritical_transaction'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/deny/$', views.validate_noncritical_transaction_denial, name='validate_noncritical_transaction_denial'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/request/$', views.validate_internal_noncritical_transaction_request, name='validate_internal_noncritical_transaction_request'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/request/approve/$', views.validate_external_noncritical_transaction_access_request_approval, name='validate_external_noncritical_transaction_access_request_approval'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/request/deny/$', views.validate_external_noncritical_transaction_access_request_denial, name='validate_external_noncritical_transaction_access_request_denial'),
    url(r'^transaction/internal_critical/$', views.internal_critical_transactions, name='internal_critical_transactions'),
    url(r'^transaction/internal_critical/(?P<transaction_id>[1-9][0-9]*)/approve/$', views.validate_internal_critical_transaction_access_request_approval, name='validate_internal_critical_transaction_access_request_approval'),
    url(r'^transaction/internal_critical/(?P<transaction_id>[1-9][0-9]*)/delete/$', views.validate_delete_internal_critical_transaction, name='validate_delete_internal_critical_transaction'),
    url(r'^transaction/internal_critical/(?P<transaction_id>[1-9][0-9]*)/deny/$', views.validate_internal_critical_transaction_access_request_denial, name='validate_internal_critical_transaction_access_request_denial'),
    url(r'^transaction/internal_noncritical/$', views.internal_noncritical_transactions, name='internal_noncritical_transactions'),
    url(r'^transaction/internal_noncritical/(?P<transaction_id>[1-9][0-9]*)/delete/$', views.validate_delete_internal_noncritical_transaction, name='validate_delete_internal_noncritical_transaction'),
]

group3_sbs/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^loggedin/$', views.loggedin, name='loggedin'),
    url(r'^validate/$', views.loginValidate, name='loginValidate'),
    url(r'^locked_out/$', views.lock_out, name='lock_out'),
    url(r'^deviceVerify/$', views.deviceVerify, name='deviceVerify'),
]

group3_sbs/internal/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator, MaxLengthValidator, MinLengthValidator
from django.db import models
from global_templates.models import Transaction
from login.models import UserProfile

# Create your models here.
class InternalEmployee(UserProfile):
    # Inner class to define meta attributes about class
    class Meta:
        # This class is abstract so no table will be created in database
        abstract = True

class RegularEmployee(InternalEmployee):
    pass

class SystemManager(InternalEmployee):
    pass

class Administrator(InternalEmployee):
    pass

class InternalNoncriticalTransaction(Transaction):
    pass

class InternalCriticalTransaction(Transaction):
    pass

class TransactionLog(models.Model):
    external_critical_transaction = models.ManyToManyField('external.ExternalCriticalTransaction')
    external_noncritical_transaction = models.ManyToManyField('external.ExternalNoncriticalTransaction')
    internal_critical_transaction = models.ManyToManyField(InternalCriticalTransaction)
    internal_noncritical_transaction = models.ManyToManyField(InternalNoncriticalTransaction)

class accessRequests(models.Model):
    internalUserId = models.IntegerField()
    externalUserId = models.IntegerField()
    pageToView = models.CharField(max_length=30)

class CreditPaymentManager(models.Model):
    last_day_late_fee_date_executed = models.DateTimeField()
    last_month_late_fee_date_executed = models.DateTimeField()

group3_sbs/internal/templates/internal/clear_log.html
{% extends "global_templates/internal_sbs.html" %}

{% load static %}

{% block stylesheets %}
<!-- Add stylesheets or javascript here !-->
{% endblock %}


{% block navigation %}
<!-- Navigation here !-->
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>Are you sure you want to clear all contents from a log?</h1>
  </div>
</div>
<br />
<div class="row">
  <div class="col-md-2">
    <form action="{% url 'internal:validate_clear_create_log' %}" method="post">
    {% csrf_token %}
      <label for="submit">Clear contents for create log?</label>
      <input type="submit" class="btn btn-danger" value="Clear Create Log" />
    </form>
  </div>
  <div class="col-md-2">
    <form action="{% url 'internal:validate_clear_external_log' %}" method="post">
    {% csrf_token %}
      <label for="submit">Clear contents for external log?</label>
      <input type="submit" class="btn btn-danger" value="Clear External Log" />
    </form>
  </div>
  <div class="col-md-2">
    <form action="{% url 'internal:validate_clear_internal_log' %}" method="post">
    {% csrf_token %}
      <label for="submit">Clear contents for internal log?</label>
      <input type="submit" class="btn btn-danger" value="Clear Internal Log" />
    </form>
  </div>
  <div class="col-md-2">
    <form action="{% url 'internal:validate_clear_login_log' %}" method="post">
    {% csrf_token %}
      <label for="submit">Clear contents for login log?</label>
      <input type="submit" class="btn btn-danger" value="Clear Login Log" />
    </form>
  </div>
  <div class="col-md-2">
    <form action="{% url 'internal:validate_clear_reset_log' %}" method="post">
    {% csrf_token %}
      <label for="submit">Clear contents for reset log?</label>
      <input type="submit" class="btn btn-danger" value="Clear Reset Log" />
    </form>
  </div>
  <div class="col-md-2">
    <form action="{% url 'internal:validate_clear_server_log' %}" method="post">
    {% csrf_token %}
      <label for="submit">Clear contents for server log?</label>
      <input type="submit" class="btn btn-danger" value="Clear Server Log" />
    </form>
  </div>
</div>
{% endblock %}

group3_sbs/internal/templates/internal/create_internal_user.html
{% extends "global_templates/internal_sbs.html" %}

{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'create/style.css' %}" />

<script type="text/javascript">
$(document).ready(function() {
    $("#username").tooltip({
    	position : {my : "left+15 center", at : "right center"}
    });

    var i;
    for (i = 1; i <= 9; i++)
     { var keyboard = "keyboard"+i;
    $("#"+keyboard).tooltip({
                position : {my : "left+15 center", at : "right center"}
              });
     }

    for (i = 11; i <= 12; i++)
     { var keyboard = "keyboard"+i;
    $("#"+keyboard).tooltip({
                position : {my : "left+15 center", at : "right center"}
              });
     }
     $('#createUserForm').bootstrapValidator({
         message: 'This value is not valid',
         feedbackIcons: {
             valid: 'glyphicon glyphicon-ok',
             invalid: 'glyphicon glyphicon-remove',
             validating: 'glyphicon glyphicon-refresh'
         },
         fields: {
             username: {
                 validators: {
                     notEmpty: {
                         message: 'The username is required'
                     },
                    regexp: {
                       regexp : /^[A-Za-z0-9]+[_@+.\-]{0,1}[A-Za-z0-9]+$/,
                       message : 'The user name should contain letters/digits/combination , followed by ONE optional characters _@+.\- , followed by letters/digits/combination'
                     },
                     stringLength: {
                       max: 150,
                       min: 6,
                       message: 'The length must be between 6 and 150'
                     }
                 }
             },
             email:   {
                 validators: {
                     notEmpty: {
                         message: 'The Email is required'
                     },
                     regexp: {
                     regexp: /^[a-zA-Z0-9\!\#\$\%\&\'\*\+\-\/\=\?\^\_\`\{\|\}\~\,\.]+@[a-zA-Z0-9\-\[]+(\.[a-zA-Z0-9\-\]]+)+$/,
                       message : 'The email format is incorrect'
                     },
                       stringLength: {
                       max: 100,
                       min: 3,
                       message: 'The length must be between 3 and 100'
                     }
                 }
             },
             confirm_password : {
               validators : {
                 notEmpty : {
                   message: 'The confirm password is required'
                 },
                 identical : {
                   field : 'new_password',
                   message : 'The confirm password must be same as password'
                 }
               }
             },
             new_password: {
                 validators: {
                     notEmpty: {
                         message: 'The password is required'
                     },
                     identical : {
                         field : 'confirmPassword',
                         message : 'The confirm password must be same as password'
                     },
                      stringLength: {
                       max: 256,
                       min: 8,
                       message: 'The length must be between 8 and 256'
                     },
                     callback: {
                        message: 'The password is not valid',
                         callback: function(value, password, $field){
                             if(value===''){
                                 return true;
                              }

                             if (value.search(/[0-9]/) < 0) {
                                 return {
                                     valid: false,
                                     message: 'Password must contain atleast 1 digit'
                                 }
                             }

                         if (value.search(/[\~\`\!\@\#\$\%\^\&\*\(\)\_\-\+\=\{\}\[\]\|\\\;\:\'\"\,\<\.\>\?]/) < 0)
                              {//~`!@#$%^&*()_-+={}[]|;:‘”,<.>?
                                 return {
                                     valid: false,
                                     message: 'password must contain atleast one of these ~`!@#$%^&*()_-+={}[]|;:‘”,<.>?'
                                 }
                              }


                             if (value === value.toLowerCase()) {
                                 return {
                                     valid: false,
                                     message: 'Password must contain at least one upper case character'
                                 }
                             }

                               if (value === value.toUpperCase()) {
                                 return {
                                     valid: false,
                                     message: 'Password must contain at least one lower case character'
                                 }
                             }

                             return true;
                       }

                     }
                 }
             },
            last_name:   {
                 validators: {
                     notEmpty: {
                         message: 'The lastname is required'
                     },
                     regexp: {
                       regexp : /^[a-zA-Z]+$/,
                       message : 'The last name can contain only alphabets.'
                     },
                       stringLength: {
                       max: 30,
                       min: 1,
                       message: 'The length must be between 1 and 30'
                     }
                 }
             },
           first_name:   {
                 validators: {
                     notEmpty: {
                         message: 'The firstname is required'
                     },
                     regexp: {
                       regexp : /^[a-zA-Z]+$/,
                       message : 'The first name can contain alphabets and single space as seperator.'
                     },
                     stringLength: {
                       max: 30,
                       min: 1,
                       message: 'The length must be between 1 and 30'
                     }
                 }
             },
           street_address :  {
                 validators: {
                     notEmpty: {
                         message: 'The address is required'
                     },
                     regexp: {
                       regexp : /^[a-zA-Z0-9]+(\s?[a-zA-Z0-9]+)*$/,
                       message : 'The address should contain only alphabets and single space as seperator'
                     },
                     stringLength: {
                       max: 30,
                       min: 4,
                       message: 'The length must be between 4 and 30'
                     }
                 }
             },
             city :  {
                 validators: {
                     notEmpty: {
                         message: 'The city is required'
                     },
                     regexp: {
                       regexp : /^[a-zA-Z]+(\s?[a-zA-Z]+)*$/,
                       message : 'The city should contain only alphabets and single space as seperator'
                     },
                     stringLength: {
                       max: 30,
                       min: 4,
                       message : 'The length must be between 4 and 30'
                     }
                 }
             },
             zipcode : {
                 validators: {
                     notEmpty: {
                         message: 'The zip code is required'
                     },
                     regexp: {
                       regexp : /^\d{5}$/,
                       message : 'The zip code should contain only 5 digits'
                     }
                 }
             }
         }
     });
});
</script>
{% endblock %}

{% block navigation %}
{% endblock %}
{% block content %}
<h1>Create New Internal User</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="container">
<div class="col-md-12 col-md-offset-0">

<form id="createUserForm" action="{% url 'internal:validate_create_internal_user' %}" method="post" class="form-horizontal">
{% csrf_token %}

<div class="form-group">
    <label class="control-label">Username</label>
      <input type="text" id="keyboard1" class="form-control" name="username" value="" placeholder="Username" title="Length must be between 6 to 150 ; consist of alphabet/digits/combination , followed by one optional character in the set _@+.- , followed by alphabet/digits/combination" required />
      <img id="icon1" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="text" class="form-control" name="username" value="" required /> -->

<div class="form-group">
    <label class="control-label">Email</label>
     <input type="text" id="keyboard2" class="form-control" name="email" value="" placeholder="Email" title="Length must be between 3 to 100; Should follow the correct email format " required />
     <img id="icon2" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>

<!-- <input type="password" class="form-control" name="otpPassword" value="" required /> -->
<div class="form-group"> <label class="control-label">Set New Password</label>
<input type="password" id="keyboard4" class="form-control" name="new_password" value="" placeholder="New Password" title="Length must be between 8 and 256; Should have atleast One uppercase, AND atleast one lowecase AND atleast one digit and atleast one character in this set ~`!@#$%^&*()_-+={}[]|;:‘”,<.>? " required />
      <img id="icon4" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="password" class="form-control" name="newPassword" value="" required /> -->
<div class="form-group"> <label class="control-label">Confirm New Password</label>
<input type="password" id="keyboard5" class="form-control" name="confirm_password" value="" placeholder="Confirm Password" title="Must match the new Password field" required />
      <img id="icon5" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="password" class="form-control" name="confirmPassword" value="" required /> -->
<div class="form-group"> <label class="control-label">First Name</label>
<input type="text" id="keyboard6" class="form-control" name="first_name" value="" placeholder="First Name" title="length between 1 and 30. upper OR lowercase OR combination of both;" required />
      <img id="icon6" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="text" class="form-control" name="firstname" value="" required /> -->
<div class="form-group"> <label class="control-label">Last Name</label>
<input type="text" id="keyboard7" class="form-control" name="last_name" value="" placeholder="Last Name" title="length between 1 and 30. upper OR lowercase Or combination of both" required />
      <img id="icon7" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="text" class="form-control" name="lastname" value="" required /> -->
<div class="form-group"> <label class="control-label">Street Address</label>
<input type="text" id="keyboard8" class="form-control" name="street_address" value="" placeholder="Street Address" title="between 4 and 30. upper OR lowercase OR digit OR combination of all ; should not start or end with space; only one space allowed between characters. " required />
      <img id="icon8" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="text" class="form-control" name="address" value="" required /> -->
<div class="form-group"> <label class="control-label">City</label>
 <input type="text" id="keyboard9" class="form-control" name="city" value="" placeholder="City" title="length between 4 and 30. upper OR lowercase OR combination of both; should not start or end with space ;  only one space allowed between characters." required />
      <img id="icon9" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="text" class="form-control" name="city" value="" required /> -->
<div class="form-group">
      <label class="control-label">State</label>
      <select class="form-control" name="state">
        {% for state in STATES %}
        <option value="{{state}}">{{state}}</option>
        {% endfor %}
      </select>
</div>
<!-- <input type="text" class="form-control" name="state" value="" required /> -->
<div class="form-group"> <label class="control-label">Zip Code</label>
 <input type="text" id="keyboard11" class="form-control" name="zipcode" value="" placeholder="Zip Code" title="Only 5 digits are allowed" required />
      <img id="icon11" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<div class="form-group">
      <label class="control-label">Select User Type</label>
      <br />
      <label class="radio-inline"><input type="radio" name="user_type" value="Regular Employee" checked="checked" required >Regular Employee</label>
      <label class="radio-inline"><input type="radio" name="user_type" value="System Manager" required >System Manager</label>
      <label class="radio-inline"><input type="radio" name="user_type" value="Administrator" required >Administrator</label>
</div>


<div class="form-group">
	<input type="submit" class="btn btn-default form-control" value="Submit" />
</div>

</form>
</div>
</div>
{% endblock %}

group3_sbs/internal/templates/internal/internal_critical_transactions.html
{% extends "global_templates/internal_sbs.html" %}

{% load static %}

{% block stylesheets %}
<!-- Add stylesheets or javascript here !-->
{% endblock %}


{% block navigation %}
<!-- Navigation here !-->
{% endblock %}

{% block content %}

{% if error_message %}
<div class="row">
  <div class="col-md-12">
    <h1>{{error_message}}</h1>
  </div>
</div>
{% endif %}

<div class="row">
  <div class="col-md-12">
    <h1>List of Internal Critical Transactions</h1>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Initiator</th>
        <th>Description</th>
        <th>Time Created</th>
        <th>Status</th>
        <th>Resolver</th>
        <th>Time Resolved</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in transactions %}
      <tr>
        <td>{{transaction.id}}</td>
        <td>{{transaction.type_of_transaction}}</td>
        <td>{{transaction.initiator.username}}</td>
        <td>{{transaction.description}}</td>
        <td>{{transaction.time_created}}</td>
        <td>{{transaction.status}}</td>
        {% if transaction.resolver %}
        <td>{{transaction.resolver.username}}</td>
        <td>{{transaction.time_resolved}}</td>
        {% else %}
        <td>Unresolved</td>
        <td>Unresolved</td>
        {% endif %}
        <td>
          <form action="{% url 'internal:validate_internal_critical_transaction_access_request_approval' transaction_id=transaction.id %}" method="post">
            {% csrf_token %}<input type="submit" class="btn btn-primary" value="Approve" />
          </form>
          <form action="{% url 'internal:validate_internal_critical_transaction_access_request_denial' transaction_id=transaction.id %}" method="post">
            {% csrf_token %}<input type="submit" class="btn btn-warning" value="Deny" />
          </form>
          <form action="{% url 'internal:validate_delete_internal_critical_transaction' transaction_id=transaction.id %}" method="post">
            {% csrf_token %}<input type="submit" class="btn btn-danger" value="Delete" />
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
    </tfoot>
  </table>
</div>
{% endblock %}

group3_sbs/internal/templates/internal/internal_noncritical_transactions.html
{% extends "global_templates/internal_sbs.html" %}

{% load static %}

{% block stylesheets %}
<!-- Add stylesheets or javascript here !-->
{% endblock %}


{% block navigation %}
<!-- Navigation here !-->
{% endblock %}

{% block content %}

{% if error_message %}
<div class="row">
  <div class="col-md-12">
    <h1>{{error_message}}</h1>
  </div>
</div>
{% endif %}

<div class="row">
  <div class="col-md-12">
    <h1>List of Internal Non-Critical Transactions</h1>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Initiator</th>
        <th>Description</th>
        <th>Time Created</th>
        <th>Status</th>
        <th>Resolver</th>
        <th>Time Resolved</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in transactions %}
      <tr>
        <td>{{transaction.id}}</td>
        <td>{{transaction.type_of_transaction}}</td>
        <td>{{transaction.initiator.username}}</td>
        <td>{{transaction.description}}</td>
        <td>{{transaction.time_created}}</td>
        <td>{{transaction.status}}</td>
        {% if transaction.resolver %}
        <td>{{transaction.resolver.username}}</td>
        <td>{{transaction.time_resolved}}</td>
        {% else %}
        <td>Unresolved</td>
        <td>Unresolved</td>
        {% endif %}
        <td>
          <form action="{% url 'internal:validate_external_noncritical_transaction_access_request_approval' transaction_id=transaction.id %}" method="post">
            {% csrf_token %}<input type="submit" class="btn btn-primary" value="Approve" />
          </form>
          <form action="{% url 'internal:validate_external_noncritical_transaction_access_request_denial' transaction_id=transaction.id %}" method="post">
            {% csrf_token %}<input type="submit" class="btn btn-warning" value="Deny" />
          </form>
          <form action="{% url 'internal:validate_delete_internal_noncritical_transaction' transaction_id=transaction.id %}" method="post">
            {% csrf_token %}<input type="submit" class="btn btn-danger" value="Delete" />
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
    </tfoot>
  </table>
</div>
{% endblock %}