group3_sbs/external/urls.py
from django.conf.urls import url
from . import views

app_name = 'external'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^account/addPaymentRequestToDB/$', views.addPaymentRequestToDB, name='add_merchantPaymentRequest_toDB'),
    url(r'^account/credit/checking/$', views.credit_checking, name='credit_checking'),
    url(r'^account/credit/checking/validate/$', views.credit_checking_validate, name='credit_checking_validate'),
    url(r'^account/credit/savings/$', views.credit_savings, name='credit_savings'),
    url(r'^account/credit/savings/validate/$', views.credit_savings_validate, name='credit_savings_validate'),
    url(r'^account/critical_challenge_response/(?P<account_type>[a-zA-z]+)/(?P<type_of_transaction>[a-zA-z]+)/$', views.critical_challenge_response, name='critical_challenge_response'),
    url(r'^account/critical_challenge_response/(?P<account_type>[a-zA-z]+)/(?P<type_of_transaction>[a-zA-z]+)/validate/$', views.critical_challenge_response_validate, name='critical_challenge_response_validate'),
    url(r'^account/debit/checking/$', views.debit_checking, name='debit_checking'),
    url(r'^account/debit/checking/validate/$', views.debit_checking_validate, name='debit_checking_validate'),
    url(r'^account/debit/savings/$', views.debit_savings, name='debit_savings'),
    url(r'^account/debit/savings/validate/$', views.debit_savings_validate, name='debit_savings_validate'),
    url(r'^account/email_payment/checking/$', views.payment_email_checking, name='payment_email_checking'),
    url(r'^account/email_payment/savings/$', views.payment_email_savings, name='payment_email_savings'),
    #url(r'^account/email_payment_on_behalf/checking/$', views.payment_on_behalf_email_checking, name='payment_on_behalf_email_checking'),
    #url(r'^account/email_payment_on_behalf/savings/$', views.payment_on_behalf_email_savings, name='payment_on_behalf_email_savings'),
    url(r'^account/email_transfer/checking/$', views.transfer_email_checking, name='transfer_email_checking'),
    url(r'^account/email_transfer/savings/$', views.transfer_email_savings, name='transfer_email_savings'),
    url(r'^account/payment/checking/$', views.payment_checking, name='payment_checking'),
    url(r'^account/payment/checking/validate/$', views.payment_checking_validate, name='payment_checking_validate'),
    url(r'^account/payment/savings/$', views.payment_savings, name='payment_savings'),
    url(r'^account/payment/savings/validate/$', views.payment_savings_validate, name='payment_savings_validate'),
    #url(r'^account/payment_on_behalf/checking/$', views.payment_on_behalf_checking, name='payment_on_behalf_checking'),
    #url(r'^account/payment_on_behalf/checking/validate/$', views.payment_on_behalf_checking_validate, name='payment_on_behalf_checking_validate'),
    #url(r'^account/payment_on_behalf/savings/$', views.payment_on_behalf_savings, name='payment_on_behalf_savings'),
    #url(r'^account/payment_on_behalf/savings/validate/$', views.payment_on_behalf_savings_validate, name='payment_on_behalf_savings_validate'),
    url(r'^account/request/access/approve/$', views.approveAccessRequests, name='approve_access_approvals'),
    url(r'^account/request/access/reject/$', views.rejectAccessRequests, name='reject_access_approvals'),
    url(r'^account/request/access/view/$', views.getAccessRequests, name='get_Accessrequests'),
    url(r'^account/request/payment/$', views.request_payment, name='request_payment'),
    url(r'^account/request/payment/approve/$', views.update_approvals, name='update_approvals'),
    url(r'^account/request/payment/deny/$', views.reject_approvals, name='reject_approvals'),
    url(r'^account/request/payment/email/$', views.request_payment_email, name='request_payment_email'),
    url(r'^account/request/show/$', views.showPaymentRequests, name='showPaymentRequests'),
    url(r'^account/transfer/checking/$', views.transfer_checking, name='transfer_checking'),
    url(r'^account/transfer/checking/validate/$', views.transfer_checking_validate, name='transfer_checking_validate'),
    url(r'^account/transfer/savings/$', views.transfer_savings, name='transfer_savings'),
    url(r'^account/transfer/savings/validate/$', views.transfer_savings_validate, name='transfer_savings_validate'),
    url(r'^account/update_approvals/$', views.update_approvals, name='update_approvals'),
    url(r'^account/view/checking/$', views.checking_account, name='checking_account'),
    url(r'^account/view/savings/$', views.savings_account, name='savings_account'),
    url(r'^account/view/statements/all/$', views.all_statements, name='all_statements'),
    url(r'^account/view/statements/all/pdf/$', views.all_statements_pdf, name='all_statements_pdf'),
    url(r'^account/view/statements/checking_and_savings/pdf/$', views.checking_and_savings_statements_pdf, name='checking_and_savings_statements_pdf'),
    url(r'^account/view/statements/checking_and_savings/view/$', views.checking_and_savings_statements, name='checking_and_savings_statements'),
    url(r'^account/view/statements/credit_card/pdf/$', views.credit_card_statements_pdf, name='credit_card_statements_pdf'),
    url(r'^account/view/statements/credit_card/view/$', views.credit_card_statements, name='credit_card_statements'),
    url(r'^credit_card/charge/validate/$', views.credit_card_debit_charge_limit_validate, name='credit_card_debit_charge_limit_validate'),
    url(r'^credit_card/payment/late/validate/$', views.credit_card_pay_late_fee_validation, name='credit_card_pay_late_fee_validation'),
    url(r'^credit_card/payment/validate$', views.credit_card_credit_charge_limit_validate, name='credit_card_credit_charge_limit_validate'),
    url(r'^credit_card/payment_or_charge/$', views.charge_limit, name='charge_limit'),
    url(r'^credit_card/view/$', views.show_credit_info, name='show_credit_info'),
    url(r'^error/$', views.error, name='error'),
    url(r'^profile/certificate/add/$', views.add_certificate, name='add_certificate'),
    url(r'^profile/edit/$', views.profile_edit, name='profile_edit'),
    url(r'^profile/edit/validate/$', views.profile_edit_validate, name='profile_edit_validate'),
    url(r'^profile/view/$', views.profile, name='profile'),
]

group3_sbs/group3_sbs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import global_templates.views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls', namespace='login')),
    url(r'^login/', include('login.urls', namespace='login')),
    url(r'^internal/', include('internal.urls', namespace='internal')),
    url(r'^external/', include('external.urls', namespace='external')),
    url(r'^reset/', include('reset.urls', namespace='reset')),
    url(r'^create/', include('create.urls', namespace='create')),
    url(r'^favicon.ico', global_templates.views.stop_favicon),
    url(r'^.*', include('login.urls', namespace='login')),
]

group3_sbs/internal/urls.py
from django.conf.urls import url
from . import views

app_name = 'internal'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cron_job/cron_job_late_charge/$', views.bineeta_cron_job_late_charge, name='bineeta_cron_job_late_charge'),
    url(r'^cron_job/cron_job_late_charge/validate/$', views.bineeta_cron_job_late_charge_validate, name='bineeta_cron_job_late_charge_validate'),
    url(r'^cron_job/cron_job_daily_late_charge/validate/$', views.bineeta_cron_job_daily_late_charge_validate, name='bineeta_cron_job_daily_late_charge_validate'),
    url(r'^error/$', views.error, name='error'),
    url(r'^external_user/checking_account/(?P<external_user_id>[1-9][0-9]*)/view/$', views.view_external_user_checking_account, name='view_external_user_checking_account'),
    url(r'^external_user/credit_card/(?P<external_user_id>[1-9][0-9]*)/view/$', views.view_external_user_credit_card, name='view_external_user_credit_card'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/deactivate/$', views.validate_deactivate_external_user, name='validate_deactivate_external_user'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/edit/$', views.edit_external_user_profile, name='edit_external_user_profile'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/edit/validate/$', views.validate_profile_edit, name='validate_profile_edit'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/reactivate/$', views.validate_reactivate_external_user, name='validate_reactivate_external_user'),
    url(r'^external_user/profile/(?P<external_user_id>[1-9][0-9]*)/view/$', views.view_external_user_profile, name='view_external_user_profile'),
    url(r'^external_user/request_access/$', views.external_user_access_request, name='external_user_access_request'),
    url(r'^external_user/request_access/validate/$', views.validate_external_user_access_request, name='validate_external_user_access_request'),
    url(r'^external_user/savings_account/(?P<external_user_id>[1-9][0-9]*)/view/$', views.view_external_user_savings_account, name='view_external_user_savings_account'),
    url(r'^internal_user/profile/create/$', views.create_internal_user, name='create_internal_user'),
    url(r'^internal_user/profile/create/validate/$', views.validate_create_internal_user, name='validate_create_internal_user'),
    url(r'^internal_user/profile/edit/$', views.edit_own_profile, name='edit_own_profile'),
    url(r'^internal_user/profile/edit/validate/$', views.validate_own_profile_edit, name='validate_own_profile_edit'),
    url(r'^internal_user/profile/view/$', views.view_own_profile, name='view_own_profile'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/deactivate/$', views.validate_deactivate_internal_user, name='validate_deactivate_internal_user'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/edit/$', views.edit_internal_user_profile, name='edit_internal_user_profile'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/edit/validate/$', views.validate_internal_profile_edit, name='validate_internal_profile_edit'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/reactivate/$', views.validate_reactivate_internal_user, name='validate_reactivate_internal_user'),
    url(r'^internal_user/request_access/$', views.internal_user_access_request, name='internal_user_access_request'),
    url(r'^internal_user/request_access/validate/$', views.validate_internal_user_access_request, name='validate_internal_user_access_request'),
    url(r'^internal_user/profile/(?P<internal_user_id>[1-9][0-9]*)/view/$', views.view_internal_user_profile, name='view_internal_user_profile'),
    url(r'^log/create/clear/$', views.validate_clear_create_log, name='validate_clear_create_log'),
    url(r'^log/create/view/$', views.view_create_log, name='view_create_log'),
    url(r'^log/external/clear/$', views.validate_clear_external_log, name='validate_clear_external_log'),
    url(r'^log/external/view/$', views.view_external_log, name='view_external_log'),
    url(r'^log/internal/clear/$', views.validate_clear_internal_log, name='validate_clear_internal_log'),
    url(r'^log/internal/view/$', views.view_internal_log, name='view_internal_log'),
    url(r'^log/login/clear/$', views.validate_clear_login_log, name='validate_clear_login_log'),
    url(r'^log/login/view/$', views.view_login_log, name='view_login_log'),
    url(r'^log/reset/clear/$', views.validate_clear_reset_log, name='validate_clear_reset_log'),
    url(r'^log/reset/view/$', views.view_reset_log, name='view_reset_log'),
    url(r'^log/select_log/clear/$', views.clear_log, name='clear_log'),
    url(r'^log/server/clear/$', views.validate_clear_server_log, name='validate_clear_server_log'),
    url(r'^log/server/view/$', views.view_server_log, name='view_server_log'),
    url(r'^transaction/external_critical/$', views.critical_transactions, name='critical_transactions'),
    url(r'^transaction/external_critical/(?P<transaction_id>[1-9][0-9]*)/approve/$', views.validate_critical_transaction_approval, name='validate_critical_transaction_approval'),
    url(r'^transaction/external_critical/(?P<transaction_id>[1-9][0-9]*)/delete/$', views.validate_delete_critical_transaction, name='validate_delete_critical_transaction'),
    url(r'^transaction/external_critical/(?P<transaction_id>[1-9][0-9]*)/deny/$', views.validate_critical_transaction_denial, name='validate_critical_transaction_denial'),
    url(r'^transaction/external_noncritical/$', views.noncritical_transactions, name='noncritical_transactions'),
    # url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/edit/$', views.edit_noncritical_transaction, name='edit_noncritical_transaction'),
    # url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/edit/validate/$', views.validate_edit_noncritical_transaction, name='validate_edit_noncritical_transaction'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/approve/$', views.validate_noncritical_transaction_approval, name='validate_noncritical_transaction_approval'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/delete/$', views.validate_delete_noncritical_transaction, name='validate_delete_noncritical_transaction'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/deny/$', views.validate_noncritical_transaction_denial, name='validate_noncritical_transaction_denial'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/request/$', views.validate_internal_noncritical_transaction_request, name='validate_internal_noncritical_transaction_request'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/request/approve/$', views.validate_external_noncritical_transaction_access_request_approval, name='validate_external_noncritical_transaction_access_request_approval'),
    url(r'^transaction/external_noncritical/(?P<transaction_id>[1-9][0-9]*)/request/deny/$', views.validate_external_noncritical_transaction_access_request_denial, name='validate_external_noncritical_transaction_access_request_denial'),
    url(r'^transaction/internal_critical/$', views.internal_critical_transactions, name='internal_critical_transactions'),
    url(r'^transaction/internal_critical/(?P<transaction_id>[1-9][0-9]*)/approve/$', views.validate_internal_critical_transaction_access_request_approval, name='validate_internal_critical_transaction_access_request_approval'),
    url(r'^transaction/internal_critical/(?P<transaction_id>[1-9][0-9]*)/delete/$', views.validate_delete_internal_critical_transaction, name='validate_delete_internal_critical_transaction'),
    url(r'^transaction/internal_critical/(?P<transaction_id>[1-9][0-9]*)/deny/$', views.validate_internal_critical_transaction_access_request_denial, name='validate_internal_critical_transaction_access_request_denial'),
    url(r'^transaction/internal_noncritical/$', views.internal_noncritical_transactions, name='internal_noncritical_transactions'),
    url(r'^transaction/internal_noncritical/(?P<transaction_id>[1-9][0-9]*)/delete/$', views.validate_delete_internal_noncritical_transaction, name='validate_delete_internal_noncritical_transaction'),
]

group3_sbs/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^loggedin/$', views.loggedin, name='loggedin'),
    url(r'^validate/$', views.loginValidate, name='loginValidate'),
    url(r'^locked_out/$', views.lock_out, name='lock_out'),
    url(r'^deviceVerify/$', views.deviceVerify, name='deviceVerify'),
]

group3_sbs/global_templates/models.py
from __future__ import unicode_literals
from django.core.validators import MaxValueValidator, MinValueValidator, MaxLengthValidator, MinLengthValidator
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Transaction(models.Model):

    # Attributes
    amount = models.DecimalField(validators=[MinValueValidator(0.00)], max_digits=9, decimal_places=2, null=True)
    account_type =models.CharField(max_length=200, null=True)
    status = models.CharField(max_length=200)
    time_created = models.DateTimeField(auto_now_add=True)
    type_of_transaction = models.CharField(max_length=200)
    time_resolved = models.DateTimeField(blank=True, null=True)
    description = models.TextField()

    # ForeignKey Relationships
    initiator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(class)s_initiator')
    participants = models.ManyToManyField(User, related_name='%(class)s_participants')
    resolver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(class)s_resolver', blank=True, null=True)

    # Inner class to define meta attributes about class
    class Meta:
        # This class is abstract so no table will be created in database
        abstract = True


# To Do
class CertificateAuthority():
    pass

# To Do
class PreviousPassword():
    previous_password = models.CharField(max_length=200)
    associated_user = models.ForeignKey(User, on_delete=models.CASCADE)

group3_sbs/global_templates/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Create your views here.
@login_required
def stop_favicon(request):
    return HttpResponse("favicon.ico")

group3_sbs/global_templates/templates/global_templates/external_sbs.html
{% load static %}
<html>
<title>CSE545 Group 3 Secure Banking System</title>
<head>
<!--This is for Jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- Global CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'global_templates/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'global_templates/simple-sidebar.css' %}" />

<!--Validation and tool tip below -->
<link rel="stylesheet" type="text/css" href="{% static 'global_templates/bootstrapValidator/bootstrapValidator.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'global_templates/bootstrapValidator/bootstrapValidator.min.css' %}" />
<script src="{% static 'global_templates/bootstrapValidator/bootstrapValidator.js' %}"> </script>
<script src="{% static 'global_templates/bootstrapValidator/bootstrapValidator.min.js' %}"> </script>
<link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet" />
<script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

<style>
      .ui-tooltip-content {
    font-size:10pt;
    font-family:Calibri;
   }
</style>
<script type="text/javascript">
        $(document).ready(function () {
         $(":input").bind("cut copy paste",function(e) {
         e.preventDefault();
         });

         $("form").attr('autocomplete', 'off');

       });
</script>
{% block stylesheets %}{% endblock %}
</head>
<body class="">
    <div class="container-fluid">
    <nav class="navbar navbar-top navbar-default">
        <a class="navbar-brand" href="{% url 'external:index' %}">CSE545 Group 3 Secure Banking System</a>
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'external:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'external:profile' %}">Profile</a>
          </li>
          {% block navigation %}
          {% endblock %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login:signout' %}">Sign-out</a>
          </li>
          <li class="nav-item">
            {% if request.user.individualcustomer %}
              Welcome {{request.user.individualcustomer.first_name}} {{request.user.individualcustomer.last_name}} Individual Customer
            {% elif request.user.merchantorganization %}
            Welcome {{request.user.merchantorganization.first_name}} {{request.user.merchantorganization.last_name}} Merchant / Organization
            {% endif %}
          </li>

        </ul>
    </nav>

    <!--Side Navigation Bar Added Start -->
      <div id="wrapper">
        <!-- Sidebar wrapper-->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                Menu Options
                </li>
                <li>
                     <font color="#FF7F50"> View Account Balances </font>
                              <a href="{% url 'external:checking_account' %}"> &nbsp &nbsp &nbsp Checkings </a>
                              <a href="{% url 'external:savings_account' %}"> &nbsp &nbsp &nbsp Savings </a>
                </li>
                <li>
                      <font color="#FF7F50"> Debit or Credit Account </font>
                              <a href="{% url 'external:credit_checking' %}"> &nbsp &nbsp &nbsp Credit Checkings Account </a>
                              <a href="{% url 'external:debit_checking' %}"> &nbsp &nbsp &nbsp Debit Checkings Account </a>
                              <a href="{% url 'external:credit_savings' %}"> &nbsp &nbsp &nbsp Credit Savings Account </a>
                              <a href="{% url 'external:debit_savings' %}"> &nbsp &nbsp &nbsp Debit Savings Account </a>

                </li>
                <li>
                    <font color="#FF7F50"> Make Payment </font>
                              <a href="{% url 'external:payment_checking' %}"> &nbsp &nbsp &nbsp Checkings Account </a>
                              <a href="{% url 'external:payment_savings' %}"> &nbsp &nbsp &nbsp Savings Account </a>
                </li>
                 <li>
                    <font color="#FF7F50"> Make Payment by Email Address  </font>
                              <a href="{% url 'external:payment_email_checking' %}"> &nbsp &nbsp &nbsp Checkings Account </a>
                              <a href="{% url 'external:payment_email_savings' %}"> &nbsp &nbsp &nbsp Savings Account </a>
                </li>
                <li>
                    <font color="#FF7F50"> Transfer Funds</font>
                              <a href="{% url 'external:transfer_checking' %}"> &nbsp &nbsp &nbsp Checkings Account </a>
                              <a href="{% url 'external:transfer_savings' %}"> &nbsp &nbsp &nbsp Savings Account </a>
                </li>
                 <li>
                    <font color="#FF7F50"> Transfer Funds by Email Address  </font>
                              <a href="{% url 'external:transfer_email_checking' %}"> &nbsp &nbsp &nbsp Checkings Account </a>
                              <a href="{% url 'external:transfer_email_savings' %}"> &nbsp &nbsp &nbsp Savings Account </a>
                </li>
                <li>
                    <font color="#FF7F50">Credit Card</font>
                      <a href="{% url 'external:show_credit_info' %}" color="#FF7F50">&nbsp &nbsp &nbsp Credit Card Info</a>
                      <a href="{% url 'external:charge_limit' %}" color="#FF7F50">&nbsp &nbsp &nbsp +/- Remaining Credit</a>
                </li>

            {% if request.user.individualcustomer %}
            <li>
                <font color="#FF7F50">Payments on Behalf Requests</font>
                <a  href="{% url 'external:showPaymentRequests' %}"> &nbsp &nbsp &nbsp View Request</a>
            </li>
            {% elif request.user.merchantorganization %}
            <li>
                <font color="#FF7F50">Payments on Behalf Requests</font>
                  <a href="{% url 'external:request_payment' %}"> &nbsp &nbsp &nbsp Via Account Number</a>
                  <a href="{% url 'external:request_payment_email' %}"> &nbsp &nbsp &nbsp Via Email</a>
            </li>
            {% endif %}
            <li>
                <font color="#FF7F50"> View Transactions </font>
                <a href="{% url 'external:all_statements' %}"> &nbsp &nbsp &nbsp All  </a>
                  <a href="{% url 'external:checking_and_savings_statements' %}"> &nbsp &nbsp &nbsp Checking / Savings  </a>
                  <a href="{% url 'external:credit_card_statements' %}"> &nbsp &nbsp &nbsp Credit Card </a>
            </li>

            <li>
                <font color="#FF7F50"> Manage Permissions </font>
                <a href="{% url 'external:get_Accessrequests' %}"> &nbsp &nbsp &nbsp View Requests  </a>
            </li>                 <li>
                    -------
                 <li>

                  <li>
                    -------
                 <li>
            </ul>
        </div>
       <!-- Side Bar Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                    {% block content %}{% endblock %}
                   </div>
                </div>
            </div>
        </div>
      </div>
      <!--Side Navigation Bar Added End -->






  </body>
</html>

group3_sbs/global_templates/templates/global_templates/sbs.html
{% load static %}
<html>
<title>CSE545 Group 3 Secure Banking System</title>
<head>
<!--This is for Jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- reCaptcha -->
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <!-- Global CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'global_templates/style.css' %}"/>
<!--Validation and tool tip below -->
<link rel="stylesheet" type="text/css" href="{% static 'global_templates/bootstrapValidator/bootstrapValidator.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'global_templates/bootstrapValidator/bootstrapValidator.min.css' %}" />
<script src="{% static 'global_templates/bootstrapValidator/bootstrapValidator.js' %}"> </script>
<script src="{% static 'global_templates/bootstrapValidator/bootstrapValidator.min.js' %}"> </script>
<link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet" />
<script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

<style>
      .ui-tooltip-content {
    font-size:10pt;
    font-family:Calibri;
   }
</style>
<script type="text/javascript">
        $(document).ready(function () {
     $(":input").not("[name=otpPassword]")
         .bind("cut copy paste",function(e) {
         e.preventDefault();
         });

         $("form").attr('autocomplete', 'off');

       });
</script>
{% block stylesheets %}{% endblock %}
</head>
<body class="">
    <div class="container-fluid">
    <nav class="navbar navbar-top navbar-default">
        <a class="navbar-brand" href="{% url 'login:signin' %}">CSE545 Group 3 Secure Banking System</a>
        <ul class="nav navbar-nav">
          {% block navigation %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login:signin' %}">Sign-in</a>
          </li>
          {% endblock %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login:signout' %}">Sign-out</a>
          </li>
        </ul>
    </nav>
    </div>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>