group3_sbs/create/urls.py
from django.conf.urls import url
from . import views

app_name = 'create'
urlpatterns = [
    url(r'^$', views.create, name='create'),
    url(r'^create/$', views.createUser, name='createUser'),
    url(r'^confirmAccount/$', views.confirmAccount, name='confirmAccount'),

]

group3_sbs/group3_sbs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import global_templates.views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls', namespace='login')),
    url(r'^login/', include('login.urls', namespace='login')),
    url(r'^internal/', include('internal.urls', namespace='internal')),
    url(r'^external/', include('external.urls', namespace='external')),
    url(r'^reset/', include('reset.urls', namespace='reset')),
    url(r'^create/', include('create.urls', namespace='create')),
    url(r'^favicon.ico', global_templates.views.stop_favicon),
    url(r'^.*', include('login.urls', namespace='login')),
]

group3_sbs/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^loggedin/$', views.loggedin, name='loggedin'),
    url(r'^validate/$', views.loginValidate, name='loginValidate'),
    url(r'^locked_out/$', views.lock_out, name='lock_out'),
    url(r'^deviceVerify/$', views.deviceVerify, name='deviceVerify'),
]

group3_sbs/reset/urls.py
from django.conf.urls import url
from . import views

app_name = 'reset'
urlpatterns = [
    url(r'^$', views.reset, name='reset'),
    url(r'^reset/$', views.resetUser, name='resetUser'),
    url(r'^otpReset/$', views.otpUserReset, name='otpUserReset'),

]

group3_sbs/login/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator, MaxLengthValidator, MinLengthValidator
from django.db import models

# Create your models here.
class UserProfile(models.Model):
    # ForeignKey Relationships
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Attributes
    first_name = models.CharField(validators=[MinLengthValidator(2)], max_length=100)
    last_name = models.CharField(validators=[MinLengthValidator(2)], max_length=100)
    email = models.CharField(validators=[MinLengthValidator(3)], max_length=100, unique=True)
    street_address = models.CharField(validators=[MinLengthValidator(4)], max_length=100)
    city = models.CharField(validators=[MinLengthValidator(2)], max_length=100)
    state = models.CharField(validators=[MinLengthValidator(2)], max_length=2)
    zipcode = models.CharField(validators=[MinLengthValidator(5)], max_length=5)
    session_key = models.CharField(max_length=100)
    otp_pass = models.CharField(validators=[MinLengthValidator(13)], max_length=13, default="")
    otp_timestamp = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    trusted_device_keys = models.CharField(max_length=110, default="")

    # Inner class to define meta attributes about class
    class Meta:
        # This class is abstract so no table will be created in database
        abstract = True

group3_sbs/login/views.py
from axes.decorators import watch_login
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader, RequestContext
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.cache import never_cache
from global_templates.constants import OTP_EXPIRATION_DATE, TRUSTED_DEVICE_EXPIRY
from global_templates.common_functions import validate_password, validate_user_type, validate_username, get_user_email, get_any_user_profile, get_user_trusted_keys, trustedDeviceKeyGenerator, otpGenerator
from django.core.mail import send_mail
import datetime, time, logging

logger = logging.getLogger('login')

# Create your views here
DEBUG = False

TRUSTED_DEVICE_MESSAGE =  "Hello Group3SBS User,\n\r" +\
                          "You have recently attempted logging in to your account from an unrecognized new device.\n\r" +\
                          "To continue with verifying the device for use please use the provided confirmation code\n\r" +\
                          "to verify you trust this device for future logins. This confirmation code has an expiration time of\n\r" +\
                          "15 minutes, after which you will need to attempt logging in again to re-start device verification.\n\r" +\
                          "\n\r" +\
                          "Your confirmation code is: %s\n\r" +\
                          "\n\r" +\
                          "Please continue to verify the device by entering the above confirmation code.\n\r" +\
                          "\n\r"

# Verify Device
@watch_login
def deviceVerify(request):
    if DEBUG: print("The deviceVerify function has been called\n")
    try:
        profile = get_any_user_profile(request.POST['username'],request.POST['email'])
        reCaptcha = request.POST['g-recaptcha-response']
        if(profile and reCaptcha):
            logger.info("User:'%s' attemptting login"%(profile.user.username))
            if DEBUG: print("The username, email, and captcha have been verified\n")
            otpPassword = request.POST['otpPassword']
            if DEBUG: print("OTP code is '%s'\n"%(otpPassword))
            if((profile.otp_timestamp + OTP_EXPIRATION_DATE) >= int(time.time())):
                if(profile.otp_pass == otpPassword):
                    if DEBUG: print("Confirmed the user OTP key")
                    trusted_keys = get_user_trusted_keys(profile)
                    new_key = trustedDeviceKeyGenerator()

                    if(trusted_keys is None):
                        trusted_keys = [new_key]
                    elif(len(trusted_keys) == 10):
                        trusted_keys.pop()
                        trusted_keys.insert(0, new_key)
                    else:
                        trusted_keys.insert(0, new_key)

                    if DEBUG: print("trusted keys is:")
                    if DEBUG: print(trusted_keys)
                    if DEBUG: print("Update list of keys")
                    serial_keys = ''
                    for key in trusted_keys:
                        serial_keys += key + ';'

                    if DEBUG: print("Serialized keys '%s'"%(serial_keys))

                    profile.trusted_device_keys = serial_keys
                    profile.otp_timestamp = time.time() - OTP_EXPIRATION_DATE
                    profile.save()

                    if DEBUG: print("Update user profile keys and OTP")

                    oneYear = datetime.datetime.now()
                    oneYear.replace(year = oneYear.year + 1)

                    if DEBUG: print("Get cookie expiration")
                    user = profile.user
                    login(request, user)
                    response = redirect('login:signin')
                    if DEBUG: print("Generate response")
                    response.set_cookie('trusted_device',new_key,max_age=TRUSTED_DEVICE_EXPIRY)
                    if DEBUG: print("Finish verifying device, return response")
                    return response
                else:
                    return render(request, 'login/deviceVerify.html', {'error_message': "Incorrect OTP password",}, status=401)
            else:
                return HttpResponseRedirect(reverse('login:signin'))
        else:
            return render(request, 'login/deviceVerify.html', {'error_message': "Incorrect username and email combination or missing reCaptcha",}, status=401)
    except:
        if DEBUG: print("Threw an exception, did not complete try-block")
        return render(request, 'login/deviceVerify.html', status=401)

# Lockout Page
@never_cache
def lock_out(request):
    return render(request, 'login/lock_out.html')

# Logged in page
@never_cache
@login_required
def loggedin(request):
    user = request.user
    if (hasattr(user, 'regularemployee') or hasattr(user, 'systemmanager') or hasattr(user, 'administrator')) and (hasattr(user, 'individualcustomer') or hasattr(user, 'merchantorganization')):
        user.delete()
        return HttpResponseRedirect(reverse('login:signin'))
    else:
        # if there is a cookie for the device
        #   get the user profile
        #   check to see if the cookie stored on the device is in the list of trusted device keys
        #   if the device is trusted
        #       proceed to log in
        #   else
        #       send the user an OTP for verifying the device
        #       redirect the user to an OTP device verification page
        # else
        #   send the user an OTP for verifying the device
        #   redirect the user to an OTP device verification page

        user_email = get_user_email(user)
        profile = get_any_user_profile(user.username, user_email)
        if DEBUG: print("Current cookies:")
        if DEBUG: print request.COOKIES
        trusted_key = request.COOKIES.get('trusted_device')
        if(trusted_key != ''):
            if DEBUG: print("The 'trusted_device' cookie is present\n")
            trusted_keys = get_user_trusted_keys(profile)
            if(trusted_keys is None):
               trusted_keys = []

            if DEBUG: print("The 'trusted_device' cookie value is '%s'\n"%(trusted_key))

            if(not (trusted_key in trusted_keys)):
                if DEBUG: print("The 'trusted_device' cookie is not in the list\n")
                logout(request)
                return send_device_verify_otp(request, profile)
            else:
                if DEBUG: print("trusted key is:")
                if DEBUG: print trusted_key
                update_key = trustedDeviceKeyGenerator()
                if DEBUG: print("updated key is:")
                if DEBUG: print update_key
                trusted_keys.pop(trusted_keys.index(trusted_key))
                trusted_keys.insert(0,update_key)

                if DEBUG: print("trusted keys is:")
                if DEBUG: print trusted_keys
                if DEBUG: print("Update list of keys")
                serial_keys = ''
                for key in trusted_keys:
                    serial_keys += key + ';'

                if DEBUG: print("Serialized keys '%s'"%(serial_keys))

                profile.trusted_device_keys = serial_keys
                profile.otp_timestamp = time.time() - OTP_EXPIRATION_DATE
                profile.save()

            if hasattr(user, 'regularemployee') or hasattr(user, 'systemmanager') or hasattr(user, 'administrator'):
                response = redirect('internal:index')
                response.set_cookie('trusted_device',update_key,max_age=TRUSTED_DEVICE_EXPIRY)
                return response
            elif hasattr(user, 'individualcustomer') or hasattr(user, 'merchantorganization'):
                response = redirect('external:index')
                response.set_cookie('trusted_device',update_key,max_age=TRUSTED_DEVICE_EXPIRY)
                return response
            else:
                return HttpResponseRedirect(reverse('login:signout'))
        else:
            if DEBUG: print("The 'trusted_device' cookie is not present\n")
            logout(request)
            return send_device_verify_otp(request, profile)

# Validate login
@never_cache
@watch_login
def loginValidate(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
        reCaptcha = request.POST['g-recaptcha-response']
        user = authenticate(username=username, password=password)
        if not reCaptcha:
            raise Exception('Are you a bot? Please fill out Recapchta.')
        if user is not None and validate_user_type(user, request.POST['user_type']) and validate_username(username=username) and validate_password(password=password):
            login(request, user)
            logger.info("User:'%s' attemptting login"%(username))
            return HttpResponseRedirect(reverse('login:loggedin'))
        else:
            logger.info("User:'%s' incorrect login"%(username))
            raise Exception('Incorrect username and password combination')
    except Exception as badPassword:
        return render(request, 'login/signin.html', {'error_message': badPassword[0],}, status=401)
    except:
        return render(request, 'login/signin.html', {'error_message': "Error occurred with submission",}, status=401)

# Login Page
@never_cache
def signin(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login:loggedin'))
    else:
        return render(request, 'login/signin.html')

# Logout
@never_cache
def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login:signin'))

# Verify OTP
def send_device_verify_otp(request, profile):
    if((profile.otp_timestamp + OTP_EXPIRATION_DATE) >= int(time.time())):
        #

group3_sbs/login/templates/login/add.html
{% extends "global_templates/sbs.html" %}

{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
{% endblock %}

{% block navigation %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'login:signin' %}">Sign-in</a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="{% url 'login:add' %}">Sign-in<span class="sr-only">(current)</span></a>
</li>
{% endblock %}

{% block content %}
<h1>Add Two Numbers</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if result %}<h2><strong>The result: {{ add1 }} + {{ add2 }} = {{ result }}</strong></h2>{% endif %}

<form action="{% url 'login:addNumbers' %}" method="post">
{% csrf_token %}
<label for="firstnumber">First Number</label>
<input type="number" class="form-control" name="number1" value="0" required />
<label for="secondnumber">Second Number</label>
<input type="number" class="form-control" name="number2" value="0" required />
<input type="submit" class="btn btn-default" value="Add Numbers" />
</form>

{% endblock %}

group3_sbs/login/templates/login/deviceVerify.html
{% extends "global_templates/sbs.html" %}

{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'global_templates/keyboard/jquery-ui.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'global_templates/keyboard/keyboard.css' %}" />
<script src="{% static 'global_templates/keyboard/jquery.keyboard.extension-autocomplete.js' %}"> </script>
<script src="{% static 'global_templates/keyboard/jquery.keyboard.extension-typing.js' %}"> </script>
<script src="{% static 'global_templates/keyboard/jquery.keyboard.js' %}"></script>
<script src="{% static 'global_templates/keyboard/jquery.mousewheel.js' %}"> </script>

<script type="text/javascript">
$( document ).ready(function() {

   $('#deviceVerifyForm').bootstrapValidator({
        message: 'This value is not valid',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            username: {
                validators: {
                     callback: {
                        callback: function(value, username, $field){
                            if (value == "") {
                              return {
                                valid: false,
                                message: 'The user name cannot be empty'
                              }
                            }

                            if (value.search(/^[A-Za-z0-9]+[_@+.\-]{0,1}[A-Za-z0-9]+$/) < 0) {
                                return {
                                    valid: false,
                                    message: 'The user name is invalid'
                                }
                            }
                            if (value.length < 6 && value.length > 150 ) {
                                return {
                                  valid: false,
                                  message: 'The user name is invalid'
                                }

                            }

                            return true;

                           }

                    }
                }
            },
            email:   {
                validators: {
                    callback: {
                              callback: function(value, otpPassword, $field){
                                  if (value == "")
                                  {
                                    return {
                                      valid: false,
                                      message: 'The email cannot be empty'
                                    }

                                  }
                                  if (value.search(/^[a-zA-Z0-9\!\#\$\%\&\'\*\+\-\/\=\?\^\_\`\{\|\}\~\,\.]+@[a-zA-Z0-9\-\[]+(\.[a-zA-Z0-9\-\]]+)+$/) < 0)
                                  {
                                    return {
                                      valid: false,
                                      message: 'Invalid email format'
                                    }
                                  }

                                  if ((value.length < 3) && (value.length>100) ) {
                                    return {
                                  valid: false,
                                  message: 'Invalid email format'
                                     }

                                  }

                                  return true;

                                  }

                    }
                }
            },
            otpPassword: {
               validators: {
                    callback: {
                        callback: function(value, otpPassword, $field){
                            if (value == "") {
                              return {
                                valid: false,
                                message: 'OTP cannot be empty'
                              }
                            }
                            /*
                            if (value.search(/^[a-zA-Z0-9]+$/) < 0) {
                                return {
                                    valid: false,
                                    message: 'Invalid OTP'
                                }
                            }
                            if (value.length != 13 ) {
                                return {
                                  valid: false,
                                  message: 'Invalid OTP'
                                }

                            }
                            */
                            return true;

                           }

                    }
                }
            },
        }
    });
  $('#keyboard1').keyboard({ caretToEnd: false, openOn: '',preventPaste : true}).addTyping({ showTyping: true, delay: 50 });
  $('#keyboard2').keyboard({ caretToEnd: false, openOn: '',preventPaste : true}).addTyping({ showTyping: true, delay: 50 });
  $('#keyboard3').keyboard({ caretToEnd: false, openOn: '',preventPaste : true}).addTyping({ showTyping: true, delay: 50 });

// Open keyboard by clicking on icon
$('#icon1').click(function () { $('#keyboard1').getkeyboard().reveal(); });
$('#icon2').click(function () { $('#keyboard2').getkeyboard().reveal(); });
$('#icon3').click(function () { $('#keyboard3').getkeyboard().reveal(); });

});
</script>

{% endblock %}


{% block navigation %}
<li class="nav-item active">
  <a class="nav-link" href="{% url 'login:signin' %}">Sign-in<span class="sr-only">(current)</span></a>
</li>
{% endblock %}
{% block content %}
<h1>New Device Verification</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'login:deviceVerify' %}" method="post" id="deviceVerifyForm">
{% csrf_token %}
<p>You are attempting to login from an unrecognized device, please check your email for a confirmation code to verify your device before login.</p>
<label for="username">Username</label>
<div class="form-group"> <input type="text" id="keyboard1" class="form-control" name="username" value="" placeholder="Username"  />
	    <img id="icon1" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="text" class="form-control" name="username" value="" required /> -->
<label for="email">Email</label>
<div class="form-group"> <input type="text" id="keyboard2" class="form-control" name="email" value="" placeholder="Email"  />
	    <img id="icon2" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="email" class="form-control" name="email" value="" required /> -->
<label for="password">Confirmation Code (OTP)</label>
<div class="form-group"> <input type="password" id="keyboard3" class="form-control" name="otpPassword" value="" placeholder="OTP Password"  />
	    <img id="icon3" src="{% static 'global_templates/images/keyboard.png' %}"/>
</div>
<!-- <input type="password" class="form-control" name="otpPassword" value="" required /> -->
<br></br>
<div class="g-recaptcha" data-sitekey="6LeHWAcUAAAAAL_TtxsIcRhoC3IrD6yKdJNp0E2N"></div>
<br></br>
<input type="submit" class="btn btn-default" value="Submit" />
</form>
{% endblock %}

group3_sbs/login/templates/login/lockout.html
{% extends "global_templates/sbs.html" %}
{% load static %}
{% block content %}
  <h1>You are locked out</h1>
  <p>You attempted to access the same account three times in a row from the same IP with the same username without correctly entering a correct username password combination</p>
  <p>Please attempt to log back in after 1 hour from your last incorrect login attempt</p>
{% endblock %}

group3_sbs/login/templates/login/signin.html
{% extends "global_templates/sbs.html" %}

{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'global_templates/keyboard/jquery-ui.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'global_templates/keyboard/keyboard.css' %}" />
<script src="{% static 'global_templates/keyboard/jquery.keyboard.extension-autocomplete.js' %}"> </script>
<script src="{% static 'global_templates/keyboard/jquery.keyboard.extension-typing.js' %}"> </script>
<script src="{% static 'global_templates/keyboard/jquery.keyboard.js' %}"></script>
<script src="{% static 'global_templates/keyboard/jquery.mousewheel.js' %}"> </script>

<script src='https://www.google.com/recaptcha/api.js'></script>

<script type="text/javascript">
$( document ).ready(function() {

$('#keyboard').keyboard({
    // caret places at the end of any text
    caretToEnd: false,
    preventPaste : true,
    // Event (namespaced) on the input to reveal the keyboard.
    // To disable it, just set it to ''.
    openOn: ''
})
.addTyping({
    showTyping: true,
    delay: 50
});

// Open keyboard by clicking on icon
$('#icon').click(function () {
    $('#keyboard').getkeyboard().reveal();
});

});
</script>

{% endblock %}


{% block navigation %}
<li class="nav-item active">
  <a class="nav-link" href="{% url 'login:signin' %}">Sign-in<span class="sr-only">(current)</span></a>
</li>
{% endblock %}
{% block content %}


<div class="row" id="section-one">
      <!--This is the strip across -->
      <div class="col-md-12" style="background-color: lightblue"> <br/>
        <!--Makes the below panel enclosing to be in the center -->
        <div class="col-md-4 col-md-offset-4">
           <div class="panel panel-default ">
              <div class="panel-heading text-center"> <h4>   Login </h4>
           </div>
           <div class="panel-body">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
				<form action="{% url 'login:loginValidate' %}" method="post">
					{% csrf_token %}
					<!-- <label for="username">Username</label>-->
					<div class="form-group"> <input type="text" class="form-control" name="username" value="" placeholder="User Name" required /> </div>
					<!-- <label for="password">Password</label>-->
					<div class="form-group"> <input type="password" id="keyboard" class="form-control" name="password" value="" placeholder="Password" required />
						    <img id="icon" src="{% static 'global_templates/images/keyboard.png' %}"/>
					 </div>

	                <!-- Panel for External Users-->
	                <div class="panel panel-danger">  <div class="panel-body">
	                    <label class="radio-inline"><input type="radio" name="user_type" value="Individual Customer" checked="checked" required >Individual Customer</label>
	                    <label class="radio-inline"><input type="radio" name="user_type" value="Merchant / Organization" required >Merchant / Organization</label>
	                </div> </div>

	                <!-- Panel for Internal Users-->
	                <div class="panel panel-danger">  <div class="panel-body">
	                  <label class="radio-inline"><input type="radio" name="user_type" value="Administrator" required >Administrator</label>
	                  <label class="radio-inline"><input type="radio" name="user_type" value="System Manager" required >System Manager</label>
	                  <label class="radio-inline"><input type="radio" name="user_type" value="Regular Employee" required >Regular Employee</label>
	                </div> </div>

					<div class="g-recaptcha" data-sitekey="6LeHWAcUAAAAAL_TtxsIcRhoC3IrD6yKdJNp0E2N"></div>


				    <input class="btn btn-lg btn-primary btn-block" type="submit" value="Log in" />
				    <br></br>
				    <a class="nav-link" href="{% url 'reset:reset' %}">Forgot Password?<span class="sr-only">(current)</span></a>
				    <br></br>
				    <a class="nav-link" href="{% url 'create:create' %}">Create New Account<span class="sr-only">(current)</span></a>
					{% endblock %}

				</form>


            </div>
        </div>
       </div>
</div>

group3_sbs/login/templates/login/test.html
{% extends "global_templates/sbs.html" %}

{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
{% endblock %}


{% block navigation %}
{% endblock %}
{% block content %}
<h1>Welcome {{first_name}} {{last_name}}</h1>
<p>Email: {{email}}</p>
<p>Street: {{street_address}}</p>
<p>City: {{city}}</p>
<p>State: {{state}}</p>
<p>Zipcode: {{zipcode}}</p>
{% endblock %}