group3_sbs/external/urls.py
from django.conf.urls import url
from . import views

app_name = 'external'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^account/addPaymentRequestToDB/$', views.addPaymentRequestToDB, name='add_merchantPaymentRequest_toDB'),
    url(r'^account/credit/checking/$', views.credit_checking, name='credit_checking'),
    url(r'^account/credit/checking/validate/$', views.credit_checking_validate, name='credit_checking_validate'),
    url(r'^account/credit/savings/$', views.credit_savings, name='credit_savings'),
    url(r'^account/credit/savings/validate/$', views.credit_savings_validate, name='credit_savings_validate'),
    url(r'^account/critical_challenge_response/(?P<account_type>[a-zA-z]+)/(?P<type_of_transaction>[a-zA-z]+)/$', views.critical_challenge_response, name='critical_challenge_response'),
    url(r'^account/critical_challenge_response/(?P<account_type>[a-zA-z]+)/(?P<type_of_transaction>[a-zA-z]+)/validate/$', views.critical_challenge_response_validate, name='critical_challenge_response_validate'),
    url(r'^account/debit/checking/$', views.debit_checking, name='debit_checking'),
    url(r'^account/debit/checking/validate/$', views.debit_checking_validate, name='debit_checking_validate'),
    url(r'^account/debit/savings/$', views.debit_savings, name='debit_savings'),
    url(r'^account/debit/savings/validate/$', views.debit_savings_validate, name='debit_savings_validate'),
    url(r'^account/email_payment/checking/$', views.payment_email_checking, name='payment_email_checking'),
    url(r'^account/email_payment/savings/$', views.payment_email_savings, name='payment_email_savings'),
    #url(r'^account/email_payment_on_behalf/checking/$', views.payment_on_behalf_email_checking, name='payment_on_behalf_email_checking'),
    #url(r'^account/email_payment_on_behalf/savings/$', views.payment_on_behalf_email_savings, name='payment_on_behalf_email_savings'),
    url(r'^account/email_transfer/checking/$', views.transfer_email_checking, name='transfer_email_checking'),
    url(r'^account/email_transfer/savings/$', views.transfer_email_savings, name='transfer_email_savings'),
    url(r'^account/payment/checking/$', views.payment_checking, name='payment_checking'),
    url(r'^account/payment/checking/validate/$', views.payment_checking_validate, name='payment_checking_validate'),
    url(r'^account/payment/savings/$', views.payment_savings, name='payment_savings'),
    url(r'^account/payment/savings/validate/$', views.payment_savings_validate, name='payment_savings_validate'),
    #url(r'^account/payment_on_behalf/checking/$', views.payment_on_behalf_checking, name='payment_on_behalf_checking'),
    #url(r'^account/payment_on_behalf/checking/validate/$', views.payment_on_behalf_checking_validate, name='payment_on_behalf_checking_validate'),
    #url(r'^account/payment_on_behalf/savings/$', views.payment_on_behalf_savings, name='payment_on_behalf_savings'),
    #url(r'^account/payment_on_behalf/savings/validate/$', views.payment_on_behalf_savings_validate, name='payment_on_behalf_savings_validate'),
    url(r'^account/request/access/approve/$', views.approveAccessRequests, name='approve_access_approvals'),
    url(r'^account/request/access/reject/$', views.rejectAccessRequests, name='reject_access_approvals'),
    url(r'^account/request/access/view/$', views.getAccessRequests, name='get_Accessrequests'),
    url(r'^account/request/payment/$', views.request_payment, name='request_payment'),
    url(r'^account/request/payment/approve/$', views.update_approvals, name='update_approvals'),
    url(r'^account/request/payment/deny/$', views.reject_approvals, name='reject_approvals'),
    url(r'^account/request/payment/email/$', views.request_payment_email, name='request_payment_email'),
    url(r'^account/request/show/$', views.showPaymentRequests, name='showPaymentRequests'),
    url(r'^account/transfer/checking/$', views.transfer_checking, name='transfer_checking'),
    url(r'^account/transfer/checking/validate/$', views.transfer_checking_validate, name='transfer_checking_validate'),
    url(r'^account/transfer/savings/$', views.transfer_savings, name='transfer_savings'),
    url(r'^account/transfer/savings/validate/$', views.transfer_savings_validate, name='transfer_savings_validate'),
    url(r'^account/update_approvals/$', views.update_approvals, name='update_approvals'),
    url(r'^account/view/checking/$', views.checking_account, name='checking_account'),
    url(r'^account/view/savings/$', views.savings_account, name='savings_account'),
    url(r'^account/view/statements/all/$', views.all_statements, name='all_statements'),
    url(r'^account/view/statements/all/pdf/$', views.all_statements_pdf, name='all_statements_pdf'),
    url(r'^account/view/statements/checking_and_savings/pdf/$', views.checking_and_savings_statements_pdf, name='checking_and_savings_statements_pdf'),
    url(r'^account/view/statements/checking_and_savings/view/$', views.checking_and_savings_statements, name='checking_and_savings_statements'),
    url(r'^account/view/statements/credit_card/pdf/$', views.credit_card_statements_pdf, name='credit_card_statements_pdf'),
    url(r'^account/view/statements/credit_card/view/$', views.credit_card_statements, name='credit_card_statements'),
    url(r'^credit_card/charge/validate/$', views.credit_card_debit_charge_limit_validate, name='credit_card_debit_charge_limit_validate'),
    url(r'^credit_card/payment/late/validate/$', views.credit_card_pay_late_fee_validation, name='credit_card_pay_late_fee_validation'),
    url(r'^credit_card/payment/validate$', views.credit_card_credit_charge_limit_validate, name='credit_card_credit_charge_limit_validate'),
    url(r'^credit_card/payment_or_charge/$', views.charge_limit, name='charge_limit'),
    url(r'^credit_card/view/$', views.show_credit_info, name='show_credit_info'),
    url(r'^error/$', views.error, name='error'),
    url(r'^profile/certificate/add/$', views.add_certificate, name='add_certificate'),
    url(r'^profile/edit/$', views.profile_edit, name='profile_edit'),
    url(r'^profile/edit/validate/$', views.profile_edit_validate, name='profile_edit_validate'),
    url(r'^profile/view/$', views.profile, name='profile'),
]

group3_sbs/group3_sbs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import global_templates.views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls', namespace='login')),
    url(r'^login/', include('login.urls', namespace='login')),
    url(r'^internal/', include('internal.urls', namespace='internal')),
    url(r'^external/', include('external.urls', namespace='external')),
    url(r'^reset/', include('reset.urls', namespace='reset')),
    url(r'^create/', include('create.urls', namespace='create')),
    url(r'^favicon.ico', global_templates.views.stop_favicon),
    url(r'^.*', include('login.urls', namespace='login')),
]

group3_sbs/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^loggedin/$', views.loggedin, name='loggedin'),
    url(r'^validate/$', views.loginValidate, name='loginValidate'),
    url(r'^locked_out/$', views.lock_out, name='lock_out'),
    url(r'^deviceVerify/$', views.deviceVerify, name='deviceVerify'),
]

group3_sbs/external/views.py
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Permission
from django.core.mail import send_mail, EmailMessage
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.db.models import Q
from django.template import loader
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.cache import never_cache
from easy_pdf.rendering import render_to_pdf_response
from external.models import *
from internal.models import *
from global_templates.common_functions import *
from global_templates.constants import *
from M2Crypto import RSA, EVP
import M2Crypto, time, logging, datetime

logger = logging.getLogger('external')

# Create your views here.

""" Render Functions for Web Pages """

# View Bank Statements
@never_cache
@login_required
@user_passes_test(is_external_user)
def all_statements(request):
    user = request.user
    noncritical_transactions = ExternalNoncriticalTransaction.objects.filter(participants=user, status=TRANSACTION_STATUS_RESOLVED).order_by('time_created')
    critical_transactions = ExternalCriticalTransaction.objects.filter(participants=user, status=TRANSACTION_STATUS_RESOLVED).order_by('time_created')
    # Get all noncritical transactions for user
    # Get all critical
    transactions = []
    for transaction in noncritical_transactions:
        transactions.append(transaction)
    for transaction in critical_transactions:
        transactions.append(transaction)
    return render(request, 'external/all_statements.html',
                  {'transactions': transactions, 'title': 'All Transactions'})

# PDF All Statements
@never_cache
@login_required
@user_passes_test(is_external_user)
def all_statements_pdf(request):
    user = request.user
    noncritical_transactions = ExternalNoncriticalTransaction.objects.filter(participants=user, status=TRANSACTION_STATUS_RESOLVED).order_by('time_created')
    critical_transactions = ExternalCriticalTransaction.objects.filter(participants=user,status=TRANSACTION_STATUS_RESOLVED).order_by('time_created')
    transactions = []
    for transaction in noncritical_transactions:
        transactions.append(transaction)
    for transaction in critical_transactions:
        transactions.append(transaction)
    return render_to_pdf_response(request, 'external/all_statements_pdf.html', context={'transactions': transactions, 'username': user.username, 'title': 'All Transactions'}, filename=None, encoding=u'utf-8')

# Charge Card or Pay Card Page
@never_cache
@login_required
@user_passes_test(is_external_user)
def charge_limit(request):
    user = request.user
    profile = get_any_user_profile(username=user.username)
    if profile and has_credit_card(user):
        charge_limit = min(float(profile.credit_card.charge_limit),float(profile.credit_card.remaining_credit))
        pay_limit = float(CREDIT_CARD_MAX_BALANCE)- max(float(profile.credit_card.charge_limit),float(profile.credit_card.remaining_credit))
        return render(request, 'external/charge_limit.html', {'credit_card': profile.credit_card, 'charge_limit':charge_limit, 'pay_limit': pay_limit})
    else:
        return HttpResponseRedirect(reverse('external:error'))

# Checking Account Page
@never_cache
@login_required
@user_passes_test(is_external_user)
def checking_account(request):
    user = request.user
    if is_individual_customer(user) and has_checking_account(user):
        return render(request, 'external/checking_account.html', {'user_type': INDIVIDUAL_CUSTOMER, 'first_name': user.individualcustomer.first_name, 'last_name': user.individualcustomer.last_name,'checking_account': user.individualcustomer.checking_account, 'is_merchant_organization' : False})
    elif is_merchant_organization(user) and has_checking_account(user):
        return render(request, 'external/checking_account.html', {'user_type': MERCHANT_ORGANIZATION, 'first_name': user.merchantorganization.first_name, 'last_name': user.merchantorganization.last_name,'checking_account': user.merchantorganization.checking_account, 'is_merchant_organization' : True})
    else:
        logger.info("User %s tried to access checking account page without a checking account " % (request.user.username))
        return HttpResponseRedirect(reverse('external:error'))

# View Checking/Savings Bank Statements
@never_cache
@login_required
@user_passes_test(is_external_user)
def checking_and_savings_statements(request):
    user = request.user
    noncritical_transactions = ExternalNoncriticalTransaction.objects.filter(Q(participants=user), Q(status=TRANSACTION_STATUS_RESOLVED), ~Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_CREDIT), ~Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_DEBIT)).order_by('time_created')
    critical_transactions = ExternalCriticalTransaction.objects.filter(Q(participants=user), Q(status=TRANSACTION_STATUS_RESOLVED), ~Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_CREDIT), ~Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_DEBIT)).order_by('time_created')
    # Get all noncritical transactions for user
    # Get all critical
    transactions = []
    for transaction in noncritical_transactions:
        transactions.append(transaction)
    for transaction in critical_transactions:
        transactions.append(transaction)
    return render(request, 'external/all_statements.html',
                  {'transactions': transactions, 'title': 'Checking and Savings'})

# View Checking/Savings Bank Statements
@never_cache
@login_required
@user_passes_test(is_external_user)
def checking_and_savings_statements_pdf(request):
    user = request.user
    noncritical_transactions = ExternalNoncriticalTransaction.objects.filter(Q(participants=user), Q(status=TRANSACTION_STATUS_RESOLVED), ~Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_CREDIT), ~Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_DEBIT)).order_by('time_created')
    critical_transactions = ExternalCriticalTransaction.objects.filter(Q(participants=user), Q(status=TRANSACTION_STATUS_RESOLVED), ~Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_CREDIT), ~Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_DEBIT)).order_by('time_created')
    # Get all noncritical transactions for user
    # Get all critical
    transactions = []
    for transaction in noncritical_transactions:
        transactions.append(transaction)
    for transaction in critical_transactions:
        transactions.append(transaction)
    return render_to_pdf_response(request, 'external/all_statements_pdf.html', context={'transactions': transactions, 'username': user.username, 'title': 'Checking and Savings'}, filename=None, encoding=u'utf-8')

# Credit Card Page
@never_cache
@login_required
@user_passes_test(is_external_user)
def credit_card(request):
    user = request.user
    if is_individual_customer(user) and has_credit_card(user):
        return render(request, 'external/credit_card.html', {'user_type': INDIVIDUAL_CUSTOMER, 'first_name': user.individualcustomer.first_name, 'last_name': user.individualcustomer.last_name,'credt_card': user.individualcustomer.credit_card})
    elif is_merchant_organization(user) and has_credit_card(user):
        return render(request, 'external/credit_card.html', {'user_type': MERCHANT_ORGANIZATION, 'first_name': user.merchantorganization.first_name, 'last_name': user.merchantorganization.last_name,'credt_card': user.merchantorganization.credit_card})
    else:
        logger.info("User %s tried to access credit card page without a credit card " % (request.user.username))
        return HttpResponseRedirect(reverse('external:error'))

# View Checking/Savings Bank Statements
@never_cache
@login_required
@user_passes_test(is_external_user)
def credit_card_statements(request):
    user = request.user
    noncritical_transactions = ExternalNoncriticalTransaction.objects.filter(Q(participants=user), Q(status=TRANSACTION_STATUS_RESOLVED), Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_CREDIT) | Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_DEBIT)).order_by('time_created')
    critical_transactions = ExternalCriticalTransaction.objects.filter(Q(participants=user), Q(status=TRANSACTION_STATUS_RESOLVED), Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_CREDIT) | Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_DEBIT)).order_by('time_created')
    # Get all noncritical transactions for user
    # Get all critical
    transactions = []
    for transaction in noncritical_transactions:
        transactions.append(transaction)
    for transaction in critical_transactions:
        transactions.append(transaction)
    return render(request, 'external/all_statements.html',
                  {'transactions': transactions, 'title': 'Credit Card'})

# View Checking/Savings Bank Statements
@never_cache
@login_required
@user_passes_test(is_external_user)
def credit_card_statements_pdf(request):
    user = request.user
    noncritical_transactions = ExternalNoncriticalTransaction.objects.filter(Q(participants=user), Q(status=TRANSACTION_STATUS_RESOLVED), Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_CREDIT) | Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_DEBIT)).order_by('time_created')
    critical_transactions = ExternalCriticalTransaction.objects.filter(Q(participants=user), Q(status=TRANSACTION_STATUS_RESOLVED), Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_CREDIT) | Q(type_of_transaction=CREDIT_CARD_TRANSACTION_TYPE_DEBIT)).order_by('time_created')
    # Get all noncritical transactions for user
    # Get all critical
    transactions = []
    for transaction in noncritical_transactions:
        transactions.append(transaction)
    for transaction in critical_transactions:
        transactions.append(transaction)

group3_sbs/external/templates/external/charge_limit.html
{% extends "global_templates/external_sbs.html" %}

{% load static %}

{% block stylesheets %}
<!-- Add Stylesheets here -->
{% endblock %}


{% block navigation %}
<!-- Add Navigation here -->
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>Pay a Charge or Charge Your Card</h1>
  </div>
</div>

{% if credit_card %}
<table class="table">
  <thead>
    <tr>
      <th>Credit charge Limit</th>
      <th>Remaining Credit</th>
      <th>Late Fees</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>${{credit_card.charge_limit}}</td>
      <td>${{credit_card.remaining_credit}}</td>
      <td>${{credit_card.late_fee}}</td>
    </tr>
  </tbody>
  <tfoot>
  </tfoot>
</table>

<br />
<div class="row">
  <div class="col-md-6">
    <h2>Make a Charge on Your Card</h2>
    <form action="{% url 'external:credit_card_debit_charge_limit_validate' %}" method="post">
    {% csrf_token %}
    <label for="amount">Please enter the amount that you wish to charge to your card. It must be less than ${{charge_limit}}</label>
    <input type="number" class="form-control" name="amount" value="0.00" min="0.00" max="{{charge_limit}}" step="0.01" required />
    <input type="submit" class="btn btn-default" value="Submit" />
    </form>
  </div>
  <div class="col-md-6">
    <h2>Make a Payment on Your Charges</h2>
    <form action="{% url 'external:credit_card_credit_charge_limit_validate' %}" method="post">
    {% csrf_token %}
    <label for="amount">Please enter the amount that you wish to pay on your charges. It must be less than ${{pay_limit}}</label>
    <input type="number" class="form-control" name="amount" value="0.00" min="0.00" max="{{pay_limit}}" step="0.01" required />
    <input type="submit" class="btn btn-default" value="Submit" />
    </form>
  </div>
</div>

{% if credit_card.late_fee > 0 %}
<div class="row">
  <div class="col-md-12">
    <h2>Pay late fee</h2>
    <form action="{% url 'external:credit_card_pay_late_fee_validation' %}" method="post">
    {% csrf_token %}
    <label for="amount">Please enter the amount that you wish to pay on your late fee. It must be less than or equal to ${{credit_card.late_fee}}</label>
    <input type="number" class="form-control" name="amount" value="0.00" min="0.00" max="{{credit_card.late_fee}}" step="0.01" required />
    <input type="submit" class="btn btn-default" value="Submit" />
    </form>
  </div>
</div>
{% endif %}

{% endif %}
{% endblock %}

group3_sbs/external/templates/external/checking_account.html
{% extends "global_templates/external_sbs.html" %}

{% load static %}

{% block stylesheets %}
<!-- Add Stylesheets here -->
{% endblock %}


{% block navigation %}
<!-- Add Navigation here -->
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>Checking Account Page</h1>
  </div>
</div>

{% if checking_account %}
<table class="table">
  <thead>
    <tr>
      <th>Account Number</th>
      <th>Routing Number</th>
      <th>Current Balance</th>
      <th>Active Balance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{checking_account.id}}</td>
      <td>{{checking_account.routing_number}}</td>
      <td>${{checking_account.current_balance}}</td>
      <td>${{checking_account.active_balance}}</td>
    </tr>
  </tbody>
  <tfoot>
  </tfoot>
</table>

<br />

{% endif %}

{% endblock %}

group3_sbs/external/templates/external/debit.html
{% extends "global_templates/external_sbs.html" %}

{% load static %}

{% block stylesheets %}
<!-- Add Stylesheets here -->
{% endblock %}


{% block navigation %}
<!-- Add Navigation here -->
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>Debit your {{account_type}} Account</h1>
  </div>
</div>

{% if checking_account %}
<table class="table">
  <thead>
    <tr>
      <th>Account Number</th>
      <th>Routing Number</th>
      <th>Current Balance</th>
      <th>Active Balance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{checking_account.id}}</td>
      <td>{{checking_account.routing_number}}</td>
      <td>${{checking_account.current_balance}}</td>
      <td>${{checking_account.active_balance}}</td>
    </tr>
  </tbody>
  <tfoot>
  </tfoot>
</table>

<br />

<form action="{% url 'external:debit_checking_validate' %}" method="post">
{% csrf_token %}
{% if amount_limit > 0.0 %}
<label name="amount">Please enter an amount to debit from account greater than or equal to ${{amount_limit}}</label>
{% else %}
<label name="amount">Cannot debit the account as the balance is only ${{amount_limit}}</label>
{% endif %}
<input type="number" class="form-control" name="amount" value="0.00" min="0.00" max="{{amount_limit}}" step="0.01" required />
<input type="submit" class="btn btn-default" value="Submit" />
</form>

{% endif %}

{% if savings_account %}
<table class="table">
  <thead>
    <tr>
      <th>Account Number</th>
      <th>Routing Number</th>
      <th>Current Balance</th>
      <th>Active Balance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{savings_account.id}}</td>
      <td>{{savings_account.routing_number}}</td>
      <td>${{savings_account.current_balance}}</td>
      <td>${{savings_account.active_balance}}</td>
    </tr>
  </tbody>
  <tfoot>
  </tfoot>
</table>

<br />

<form action="{% url 'external:debit_savings_validate' %}" method="post">
{% csrf_token %}
{% if amount_limit > 0.0 %}
<label name="amount">Please enter an amount to debit from account greater than or equal to ${{amount_limit}}</label>
{% else %}
<label name="amount">Cannot debit the account as the balance is only ${{amount_limit}}</label>
{% endif %}
<input type="number" class="form-control" name="amount" value="0.00" min="0.00" max="{{amount_limit}}" step="0.01" required />
<input type="submit" class="btn btn-default" value="Submit" />
</form>

{% endif %}

{% endblock %}

group3_sbs/external/templates/external/index.html
{% extends "global_templates/external_sbs.html" %}

{% load static %}

{% block stylesheets %}
<!-- Add Stylesheets here -->
{% endblock %}


{% block navigation %}
<!-- Add Navigation here -->
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>Welcome {{first_name}} {{last_name}}</h1>
    <h2> This is the {{user_type}} page</h2>
  </div>
</div>
<div class="row">
{% if checkingaccount %}
  <div class="col-md-4">
    <a class="btn btn-info" href="{% url 'external:checking_account' %}">Access Your Checking Account</a>
  </div>
{% endif %}

{% if savingsaccount %}
  <div class="col-md-4">
    <a class="btn btn-info" href="{% url 'external:savings_account' %}">Access Your Savings Account</a>
  </div>
{% endif %}

{% if creditcard %}
  <div class="col-md-4">
    <a class="btn btn-info" href="{% url 'external:credit_card' %}">Access Your Credit Card</a>
    <a class="btn btn-info" href="{% url 'external:checking_statement' %}">Checking Bank Statements</a>
  </div>

{% endif %}
</div>

{% endblock %}

group3_sbs/external/templates/external/payment_email.html
 step="0.01"{% extends "global_templates/external_sbs.html" %}

{% load static %}

{% block stylesheets %}
<!-- Add Stylesheets here -->
{% endblock %}


{% block navigation %}
<!-- Add Navigation here -->
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>Payment from your {{account_type}} Account</h1>
  </div>
</div>

{% if checking_account %}
<table class="table">
  <thead>
    <tr>
      <th>Account Number</th>
      <th>Routing Number</th>
      <th>Current Balance</th>
      <th>Active Balance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{checking_account.id}}</td>
      <td>{{checking_account.routing_number}}</td>
      <td>${{checking_account.current_balance}}</td>
      <td>${{checking_account.active_balance}}</td>
    </tr>
  </tbody>
  <tfoot>
  </tfoot>
</table>

<br />
<form action="{% url 'external:payment_checking_validate' %}" method="post">
{% csrf_token %}
{% if amount_limit > 0.0 %}
<label name="amount">Please enter an amount less than or equal to ${{amount_limit}} to pay from your checking account</label>
{% else %}
<label name="amount">Cannot make payment from the account as the balance is only ${{amount_limit}}</label>
{% endif %}
<input type="number" class="form-control" name="amount" value="0.00" min="0.00" max="{{amount_limit}}" step="0.01" required />
<label class="radio-inline"><input type="radio" name="account_type" value="Checking" checked="checked" required />Checking</label>
<label class="radio-inline"><input type="radio" name="account_type" value="Savings" required />Savings</label>
<br />
<label for="email_address">Please enter recipient email</label>
<input type="email" class="form-control" name="email_address" value="" min="3" max="100" />
<input type="submit" class="btn btn-default" value="Submit" />
</form>

{% endif %}

{% if savings_account %}
<table class="table">
  <thead>
    <tr>
      <th>Account Number</th>
      <th>Routing Number</th>
      <th>Current Balance</th>
      <th>Active Balance</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{savings_account.id}}</td>
      <td>{{savings_account.routing_number}}</td>
      <td>${{savings_account.current_balance}}</td>
      <td>${{savings_account.active_balance}}</td>
    </tr>
  </tbody>
  <tfoot>
  </tfoot>
</table>

<br />
<form action="{% url 'external:payment_savings_validate' %}" method="post">
{% csrf_token %}
{% if amount_limit > 0.0 %}
<label name="amount">Please enter an amount less than or equal to ${{amount_limit}} to pay from your savings account</label>
{% else %}
<label name="amount">Cannot make payment from the account as the balance is only ${{amount_limit}}</label>
{% endif %}
<input type="number" class="form-control" name="amount" value="0.00" min="0.00" max="{{amount_limit}}" step="0.01" required />
<label class="radio-inline"><input type="radio" name="account_type" value="Checking" checked="checked" required />Checking</label>
<label class="radio-inline"><input type="radio" name="account_type" value="Savings" required />Savings</label>
<br />
<label for="email_address">Please enter recipient email</label>
<input type="email" class="form-control" name="email_address" value="" min="3" max="100" />
<input type="submit" class="btn btn-default" value="Submit" />
</form>

{% endif %}

{% endblock %}